apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: minio-audit-fluentd-config
    options:
      disableNameSuffixHash: false
    files:
      - fluentd.conf
      - fluentd_opensearch.conf
      - fluentd_alert.conf
      - fluentd_alert_download_filters.conf
      - fluentd_null.conf