postgres_client:
  endpoint: "load-balancer.postgres.ferlab.lan:5432"
  auth:
    ca_cert: "../../shared/postgres_ca.crt"
    password_auth: "../../shared/postgres_root_auth.yml"
    username: test
    password: test
  database: test
  connection_timeout: "5s"
  query_timeout: "5s"
terraform:
  directory: ../../postgres
  cluster_file: cluster_state.yml
patroni_client:
  endpoint: "load-balancer.postgres.ferlab.lan:4443"
  auth:
    ca_cert: "../../shared/postgres_ca.crt"
    client_cert: "../../shared/patroni_client.crt"
    client_key: "../../shared/patroni_client.key"
  request_timeout: "5s"
tests:
  switchovers: 5
  leader_losses: 5
  sync_standby_losses: 5
  leader_reboots: 5
  sync_standby_reboots: 5
  cluster_reboots: 5
  validation_interval: "10s"
  change_recover_timeout: "3m"
  loss_recover_timeout: "6m"
  reboot_recover_timeout: "3m"
  rebuild_pause: "1m"
  restart_pause: "1m"