kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-for-service
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  dataLocality: "best-effort"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pushgateway
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-for-service
  resources:
    requests:
      storage: 2Gi