apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-volume
  selector:
    matchLabels:
      environment: local-volume
