route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: slack

receivers:
  - name: slack
    slack_configs:
      - send_resolved: true
        api_url_file: /opt/alertmanager-secrets/slack_webhook
        channel: local-alerts
        icon_emoji: ":robot_face:"
        username: kvm-dev-orchestrations
        title: '{{ .CommonAnnotations.summary }}'
        text: '{{ template "slack_message" . }}'

templates:
  - templates/slack.tmpl