apiVersion: v1
kind: PersistentVolume
metadata:
  name: phenovar-mysql
spec:
  claimRef:
    name: phenovar-mysql
    namespace: phenovar
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
   - ReadWriteMany
  nfs:
    path: /opt/fs/phenovar-mysql
    server: "127.0.0.1"
  mountOptions:
    - nfsvers=4.2
    - hard
    - rw
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phenovar-mysql
  namespace: phenovar
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: phenovar-mysql