apiVersion: v1
kind: PersistentVolume
metadata:
  name: phenovar-resources-rclone
spec:
  claimRef:
    name: phenovar-resources-rclone
    namespace: phenovar-ops
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Gi
  accessModes:
   - ReadWriteMany
  nfs:
    path: /opt/fs/phenovar-resources
    server: "127.0.0.1"
  mountOptions:
    - nfsvers=4.2
    - hard
    - rw
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phenovar-resources-rclone
  namespace: phenovar-ops
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 250Gi
  storageClassName: ""
  volumeName: phenovar-resources-rclone
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: phenovar-resources
spec:
  claimRef:
    name: phenovar-resources
    namespace: phenovar
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 250Gi
  accessModes:
   - ReadOnlyMany
  nfs:
    path: /opt/fs/phenovar-resources
    server: "127.0.0.1"
    readOnly: true
  mountOptions:
    - nfsvers=4.2
    - hard
    - ro
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phenovar-resources
  namespace: phenovar
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 250Gi
  storageClassName: ""
  volumeName: phenovar-resources