---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mock-minio
  name: mock-minio
spec:
  ports:
    - name: api
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: console
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: mock-minio