apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - image: ubuntu:22.04
              name: simple-job
              command:
                - bash
              args:
                - -c
                - "sleep 5 && echo hello"

              